tusd:
  protocol: "http"
  internal_name: "tusd" #inside docker network
  #internal_name: "localhost" #inside docker network
  internal_port: "1080"
  external_name: "localhost" #outside connection hostname
  external_port:
  external_endpoint: "upload"
  endpoint: "files"
redis:
  protocol: "redis"
  username:
  password:
  host: "localhost"
  #host: "redis"
  port: "6379"
  db: 0
jwt: 
  token: "b3dc1860-b859-4a8e-8ed0-909c4734a41f"
  token_ttl: 60 #in minutes
  refresh_token_ttl : 7 #in days 