services:
  app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - tusd-network
    depends_on:
      - tusd
    volumes:
      - .:/app  # Mount the current directory for development
    environment:
      - RUST_LOG=info  # Example environment variable for Rust logging
  tusd:
    image: tusproject/tusd
    volumes:
      - ./uploads:/srv/tusd-data/data
    command: [
      "-port", "1080",
      #"-base-path", "/upload",
      "-hooks-http",
      "http://app:8080/api/uploads/hook",
      "-hooks-enabled-events=post-finish",
      "-hooks-http-retry",
      "5",
      "-behind-proxy"
    ]
    #http://app:8080/uploads/hook
    #"http://host.docker.internal:8080/uploads/hook",
    networks:
      - mon-net
      - tusd-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # Optional nginx service if you want to run it in the same compose file
  nginx:
    image: openresty/openresty:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
     # - ./certs:/etc/nginx/certs  # For SSL certificates
    depends_on:
      - app
      - tusd
    networks:
      - mon-net
      - tusd-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
  llamacpp-server:
    #https://github.com/ggml-org/llama.cpp/tree/master/examples/server
    image: ghcr.io/ggml-org/llama.cpp:server
    ports:
      - "8081:8080"
    volumes:
      - ./models:/root/.cache/llama.cpp
    command: '-hf hugging-quants/Llama-3.2-1B-Instruct-Q8_0-GGUF -c 512 --host 0.0.0.0 --port 8080'
    networks:
      - mon-net
      - tusd-network
  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - mon-net
      - tusd-network
    ports:
      - "6379:6379"
    restart: always
  transcription-worker:
    build:
      context: ./workers/transcription_worker
      dockerfile: transcription_worker.Dockerfile
    depends_on:
      - redis
    networks:
      - tusd-network
    volumes:
      - ./uploads:/app/uploads
      - ./workers/transcription_worker:/app
    environment:
      - PYTHONUNBUFFERED=1
  caption-worker:
    build:
      context: ./workers/caption_worker
      dockerfile: caption_worker.Dockerfile
    depends_on:
      - redis
    networks:
      - tusd-network
    volumes:
      - ./uploads:/app/uploads
      - ./workers/caption_worker:/app
    environment:
      - PYTHONUNBUFFERED=1
  description-worker:
    build:
      context: ./workers/description_worker
      dockerfile: description_worker.Dockerfile
    depends_on:
      - redis
    networks:
      - tusd-network
    volumes:
      - ./uploads:/app/uploads
      - ./workers/description_worker:/app
    environment:
      - PYTHONUNBUFFERED=1
networks:
  tusd-network:
    driver: bridge
  mon-net:
    driver: bridge