services:
  app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - tusd-network
    depends_on:
      - tusd
    volumes:
      - .:/app  # Mount the current directory for development
    environment:
      - RUST_LOG=info  # Example environment variable for Rust logging
  tusd:
    image: tusproject/tusd
    ports:
      - "1080:1080"
    volumes:
      - ./uploads:/srv/tusd-data/data
    command: [
      "-port", "1080",
      "-hooks-http",
      "http://app:8080/uploads/hook",
      "-hooks-enabled-events=post-finish",
      "-hooks-http-retry",
      "5"
    ]
    #http://app:8080/uploads/hook
    #"http://host.docker.internal:8080/uploads/hook",
    networks:
      - tusd-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
networks:
  tusd-network:
    driver: bridge