services:
  app:
    build: .
    networks:
      - tusd-network
      - db-network
    depends_on:
      - tusd
      - db
    volumes:
      - .:/app  # Mount the current directory for development
    environment:
      - RUST_LOG=info  # Example environment variable for Rust logging
  db:
    image: postgres:alpine
    restart: unless-stopped
    shm_size: 128mb
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 16Ozl6Q33pIf
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - db-network
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@kwik.com
      PGADMIN_DEFAULT_PASSWORD: rIW8MZ50x6z3
    ports:
      - 5000:80
    volumes:
      - pgadmindata:/var/lib/pgadmin
    networks:
      - db-network
  tusd:
    image: tusproject/tusd
    volumes:
      - ./uploads:/srv/tusd-data/data
    command: [
      "-port", "1080",
      #"-base-path", "/upload",
      "-hooks-http",
      "http://app:8080/api/uploads/hook",
      "-hooks-enabled-events=post-finish",
      "-hooks-http-retry",
      "5",
      "-behind-proxy"
    ]
    #http://app:8080/uploads/hook
    #"http://host.docker.internal:8080/uploads/hook",
    networks:
      - mon-net
      - tusd-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # Optional nginx service if you want to run it in the same compose file
  nginx:
    image: openresty/openresty:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
     # - ./certs:/etc/nginx/certs  # For SSL certificates
    depends_on:
      - app
      - tusd
    networks:
      - mon-net
      - tusd-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - mon-net
      - tusd-network
    ports:
      - "6379:6379"
    restart: always
  transcription-worker:
    build:
      context: ./workers/transcription_worker
      dockerfile: transcription_worker.Dockerfile
    depends_on:
      - redis
    networks:
      - tusd-network
    volumes:
      - ./uploads:/app/uploads
      - ./workers/transcription_worker:/app
    environment:
      - PYTHONUNBUFFERED=1
  caption-worker:
    build:
      context: ./workers/caption_worker
      dockerfile: caption_worker.Dockerfile
    depends_on:
      - redis
    networks:
      - tusd-network
    volumes:
      - ./uploads:/app/uploads
      - ./workers/caption_worker:/app
    environment:
      - PYTHONUNBUFFERED=1
  description-worker:
    build:
      context: ./workers/description_worker
      dockerfile: description_worker.Dockerfile
    depends_on:
      - redis
    networks:
      - tusd-network
    volumes:
      - ./uploads:/app/uploads
      - ./workers/description_worker:/app
    environment:
      - PYTHONUNBUFFERED=1
  quality-worker:
    build:
      context: ./workers/video_quality_worker   # Path to your quality worker folder
      dockerfile: video_quality_worker.Dockerfile                    # Dockerfile for the quality worker
    depends_on:
      - redis
    networks:
      - tusd-network
    volumes:
      - ./uploads:/app/uploads
      - ./workers/video_quality_worker:/app
    environment:
      - PYTHONUNBUFFERED=1
networks:
  tusd-network:
    driver: bridge
  db-network:

volumes:
  pgdata:
  pgadmindata: