version: '3.9'

services:
  backend:
    build:
      context: ./news_show_backend
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./news_show_backend:/app
    command: node server.js
    networks:
      - app-network

  frontend:
    build:
      context: ./news_show
    ports:
      - "5173:5173"
    working_dir: /app
    volumes:
      - ./news_show:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host 0.0.0.0

networks:
  app-network:
    driver: bridge
